name: Deploy on Github Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${GH_ACCESS_TOKEN}
          build_configuration: production
          base_href: /holiday-timer/
          deploy_branch: gh_pages
          angular_dist_build_folder: dist/app-holiday # The folder where your project is supposed to be after running ng build by the action.
